name: Build SaltyCube with Webpack

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build SaltyCube
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Yarn
      uses: mskelton/setup-yarn@v1.4.0
      with:
        node-version: 16

    - name: Build
      run: yarn build
      
    - name: Create release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
    
    - name: Upload artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/salty-cube.js
        asset_name: salty-cube.js
        asset_content_type: text/javascript
