name: Build SaltyCube with Webpack

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build SaltyCube
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Yarn
      uses: mskelton/setup-yarn@v1.4.0
      with:
        node-version: 16

    - name: Build
      run: yarn build
